from typing import Dict, Set

RESOURCES = {"PROJECT", "TASK", "USER_PROFILE", "PERMISSIONS"}
ACTIONS = {"READ", "CREATE", "UPDATE", "DELETE"}
ROLES = {"ADMIN", "MANAGER", "USER", "DELETED"}


PERMISSIONS: Set[tuple] = {

    ("ADMIN", "PROJECT", "READ"), ("ADMIN", "PROJECT", "CREATE"), ("ADMIN", "PROJECT", "UPDATE"), ("ADMIN", "PROJECT", "DELETE"),
    ("ADMIN", "TASK", "READ"), ("ADMIN", "TASK", "CREATE"), ("ADMIN", "TASK", "UPDATE"), ("ADMIN", "TASK", "DELETE"),
    ("ADMIN", "USER_PROFILE", "READ"), ("ADMIN", "USER_PROFILE", "UPDATE"),
    ("ADMIN", "PERMISSIONS", "READ"), ("ADMIN", "PERMISSIONS", "CREATE"), ("ADMIN", "PERMISSIONS", "UPDATE"), ("ADMIN", "PERMISSIONS", "DELETE"),

    
    ("MANAGER", "PROJECT", "READ"), ("MANAGER", "PROJECT", "CREATE"), ("MANAGER", "PROJECT", "UPDATE"), 
    ("MANAGER", "TASK", "READ"), ("MANAGER", "TASK", "CREATE"), ("MANAGER", "TASK", "UPDATE"),


    ("USER", "PROJECT", "READ"), 
    ("USER", "TASK", "READ"), ("USER", "TASK", "CREATE"),
    ("USER", "USER_PROFILE", "READ"), ("USER", "USER_PROFILE", "UPDATE"),
}